version: '3'
services:
 db:
  networks:
   - my_network
  build: requirements/mariadb/
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  env_file: .env

 wordpress:
  networks:
   - my_network
  depends_on:
   - db
  build: requirements/wordpress/
  volumes:
   - wp_data:/var/www
  restart: unless-stopped
  env_file: .env

 nginx:
  networks:
   - my_network
  depends_on:
   - wordpress
  build: requirements/nginx/
  volumes:
   - wp_data:/var/www
  ports:
   - "443:443"
  restart: always

volumes:
 db_data:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '${HOME}/db'
 wp_data: 
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '${HOME}/wp'

networks:
  my_network:
    driver: bridge
